routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/********************
* ROUTES - STATIC
********************/
Route::get('/', 'GameController@homepage')->name('home');

/********************
* ROUTES - PAGES
********************/
Route::get('page', 'PageController@index')->name('page.index');
Route::post('page', 'PageController@store')->name('page.store');
Route::get('page/create', 'PageController@create')->name('page.create');
Route::post('page/addcomment', 'PageController@addComment')->name('page.addcomment');
Route::put('page/{id}', 'PageController@update')->name('page.update');
Route::delete('page/{id}', 'PageController@destroy')->name('page.destroy');
Route::get('page/{slug}/edit', 'PageController@edit')->name('page.edit');

/********************
* ROUTES - GAMES
********************/
Route::get('game', 'GameController@index')->name('game.index');
Route::post('game', 'GameController@store')->name('game.store');
Route::get('game/create', 'GameController@create')->name('game.create');
//Because we might want to create a static page starting with "rent-", we have provision in the GameController@show method to push any unfound games to the appropriate PageController@show function. 
Route::get('rent-{game}', 'GameController@show')->name('game.show');
Route::get('achievements-{game}', 'GameController@achievements')->name('game.achievements');
Route::put('game/{game}', 'GameController@update')->name('game.update');
Route::delete('game/{game}', 'GameController@destroy')->name('game.destroy');
Route::get('game/{game}/edit', 'GameController@edit')->name('game.edit');
Route::post('game/addtowishlist', 'GameController@addToWishlist')->name('game.addtowishlist');
Route::post('game/deletefromwishlist', 'GameController@deleteFromWishlist')->name('game.deletefromwishlist');
Route::get('search-games', 'GameController@search')->name('game.search');

/********************
* ROUTES - PLAN
********************/
Route::get('plan', 'PlanController@index')->name('plan.index');
Route::post('plan-store', 'PlanController@store')->name('plan.store');
Route::get('plan/thanks', 'PlanController@thanks')->name('plan.thanks');
Route::get('plan/{slug}', 'PlanController@show')->name('plan.show');

/********************
* ROUTES - PRODUCTS
********************/
Route::get('cart', 'ProductController@cart')->name('product.cart');
Route::get('cart2', 'ProductController@cart2')->name('product.cart2');
Route::post('cart3', 'ProductController@cart3')->name('product.cart3');
Route::post('cart4', 'ProductController@cart4')->name('product.cart4');
Route::post('cart', 'ProductController@cartPost')->name('product.cartpost');
Route::get('product', 'ProductController@index')->name('product.index');
Route::post('product/addtocart', 'ProductController@addToCart')->name('product.addtocart');
Route::get('/product/convertcart', 'ProductController@convertCart')->name('product.convertcart');
Route::get('buy-{slug}', 'ProductController@show')->name('product.show');
Route::get('category-{slug}', 'ProductController@showcategory')->name('product.showcategory');

/********************
* ROUTES - USER
********************/
Route::get('user/account', 'UserController@account')->name('user.account');
Route::post('user/accountupdate', 'UserController@accountUpdate')->name('user.accountupdate');
Route::get('user/agelimit', 'UserController@ageLimit')->name('user.agelimit');
Route::get('user/agelimitconfirm/{hash}', 'UserController@ageLimitConfirm')->name('user.agelimitconfirm');
Route::post('user/agelimitupdate', 'UserController@ageLimitUpdate')->name('user.agelimitupdate');
Route::get('user/edit', 'UserController@edit')->name('user.edit');
Route::get('user/history', 'UserController@history')->name('user.history');
Route::get('user/invoice/{id}', 'UserController@invoiceShow')->name('user.invoiceshow');
Route::get('user/invoices', 'UserController@invoiceList')->name('user.invoicelist');
Route::get('user/subscription', 'UserController@subscription')->name('user.subscription');
Route::post('user/subscription/cancel', 'UserController@cancelSubscription')->name('user.cancelsubscription');
Route::post('user/subscription/resume', 'UserController@resumeSubscription')->name('user.resumesubscription');
Route::put('user/update', 'UserController@update')->name('user.update');
Route::post('user/register', 'UserController@registerPost')->name('user.register');
Route::get('user/registeraddress', 'UserController@registerAddress')->name('user.registeraddress');

/********************
* ROUTES - ADMIN
********************/
Route::get('admin/', 'AdminController@admin')->name('admin.admin');
Route::post('admin/assignment-run', 'AdminController@assignmentRun')->name('admin.assignmentrun');
Route::get('admin/competitors', 'AdminController@competitors')->name('admin.competitors');
Route::post('admin/competitors-post', 'AdminController@competitorsPost')->name('admin.competitorspost');
Route::post('admin/confirm-assignments', 'AdminController@confirmassignments')->name('admin.confirmassignments');
Route::get('admin/games/{numberofdays?}/{limit?}', 'AdminController@gameIndex')->name('admin.gameindex');
Route::post('admin/games-post', 'AdminController@gameIndexPost')->name('admin.gameindexpost');
Route::get('admin/igdb/{name}', 'AdminController@IGDBSearch')->name('admin.igdbsearch');
Route::get('admin/printdeliverynote/{id}', 'AdminController@printDeliveryNote')->name('admin.printdeliverynote');
Route::get('admin/product/create/', 'AdminController@productCreate')->name('admin.productcreate');
Route::get('admin/product/edit/{id}', 'AdminController@productEdit')->name('admin.productedit');
Route::get('admin/product/', 'AdminController@productIndex')->name('admin.productindex');
Route::post('admin/product/', 'AdminController@productStore')->name('admin.productstore');
Route::put('admin/product/', 'AdminController@productUpdate')->name('admin.productupdate');
Route::get('admin/rentals', 'AdminController@rentals')->name('admin.rentals');
Route::post('admin/rentals-update', 'AdminController@rentalsUpdate')->name('admin.rentalsupdate');
Route::get('admin/send-games', 'AdminController@sendGames')->name('admin.sendgames');
Route::get('admin/stock/', 'AdminController@stockIndex')->name('admin.stockindex');
Route::get('admin/stock/{id}', 'AdminController@stock')->name('admin.stock');
Route::post('admin/stock-update', 'AdminController@stockUpdate')->name('admin.stockupdate');
Route::get('admin/upload-games', 'AdminController@uploadGames')->name('admin.uploadgames');
Route::post('admin/upload-games-post', 'AdminController@uploadGamesPost')->name('admin.uploadgamespost');
Route::get('admin/upload-stock', 'AdminController@uploadStock')->name('admin.uploadstock');
Route::post('admin/upload-stock-post', 'AdminController@uploadStockPost')->name('admin.uploadstockpost');
Route::any('admin/users', 'AdminController@users')->name('admin.users');

Route::get('admin/testmail', 'AdminController@testMail')->name('admin.testmail');

/********************
* ROUTES - CONTACT
********************/
Route::get('contact', 'ContactController@create')->name('contact.create');
Route::get('contact/index', 'ContactController@index')->name('contact.index');
Route::get('contact/attachment/{slug}', 'ContactController@attachment')->name('contact.attachment');
Route::post('contact/send', 'ContactController@store')->name('contact.store');
Route::get('contact/show/{id}', 'ContactController@show')->name('contact.show');
Route::post('contact/update/', 'ContactController@update')->name('contact.update');

/********************
* ROUTES - OTHER
********************/
Route::get('braintree/token', 'BraintreeTokenController@token');
Route::post('braintree/webhook', 'WebhookController@handleWebhook');

Auth::routes();
Route::get('log-out', 'Auth\LoginController@logout')->name('log-out');

Route::get('login/{provider}', 'Auth\SocialAccountController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\SocialAccountController@handleProviderCallback');

Route::get('sitemap', 'SitemapController@index')->name('sitemap');

Route::get('{slug}', 'PageController@show')->where('slug', '(.*)')->name('page.show');

app/Cart.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Auth;
use Form;
use Request;

class Cart extends Model
{
	protected $fillable = ['product_id', 'user_id', 'ip_address', 'quantity_in_cart'];
    protected $table = 'cart';

    public function addQuantity($quantity)
    {
    	$this->quantity_in_cart = $this->quantity_in_cart + $quantity;
    	$this->save();
    }

    //For use when a user logs in to convert any lines they might have in their cart and add them to any lines they have against their user. 
    public static function convertCartToUser()
    {
        if (!Auth::check()) return false;

        $cartLinesIP   = Cart::where('ip_address', Request::ip())->get();
        $cartLinesUser = Cart::where('user_id', Auth::id())->get();

        foreach ($cartLinesUser as $line)
        {
            if ($ipLine = $cartLinesIP->where('product_id', $line->product_id)->first())
            {
                $line->quantity_in_cart = $line->quantity_in_cart + $ipLine->quantity_in_cart;
                $line->save();
                $ipLine->delete();
            }
        }

        Cart::where('ip_address', Request::ip())->update(['user_id' => Auth::id(), 'ip_address' => '']);
    }

    public static function empty()
    {
        if (Auth::check())
        {
            self::where('user_id', Auth::id())->delete();
        }
        self::where('ip_address', Request::ip())->delete();
    }

    public function getBoxAttribute()
    {
    	return '<div class="row">
    		<div class="col-6"><a href="'.route('product.show', $this->product->slug).'">'.$this->product->name.'</a></div>
    		<div class="col-2">'.
    			Form::text('cartQuantity['.$this->id.']', $this->quantity_in_cart, ['class' => 'form-control'])
    		.'</div>
    		<div class="col-2">'.$this->product->price_formatted.'</div>
    		<div class="col-2">'.$this->price_formatted.'</div>
    		</div>';
    }

    public function getBoxMiniAttribute()
    {
    	return '<div class="row">
    		<div class="col-12 col-md-7"><a href="'.route('product.show', $this->product->slug).'">'.$this->product->name.'</a></div>
    		<div class="col-4 col-md-2">'.$this->quantity_in_cart.'</div>
    		<div class="col-8 col-md-3">'.$this->price_formatted.'</div>
    		</div>';
    }

    public function getPriceAttribute()
    {
    	return $this->quantity_in_cart * $this->product->price / 100;
    }

    public function getPriceFormattedAttribute()
    {
    	return '&pound;'.number_format($this->price, 2);
    }

    //Returns the array needed to convert this into an invoice line.
    public function invoiceLineArray()
    {
        $priceArray = $this->product->priceArray();

        $return['product_id'] = $this->product_id;
        $return['quantity_invoiced'] = $this->quantity_in_cart;
        $return['net'] = $this->quantity_in_cart * $priceArray['net'];
        $return['vat'] = $this->quantity_in_cart * $priceArray['vat'];
        $return['gross'] = $this->quantity_in_cart * $priceArray['gross'];
        $return['net_per_item'] = $priceArray['net'];
        $return['vat_per_item'] = $priceArray['vat'];
        $return['gross_per_item'] = $priceArray['gross'];
        
        return $return;
    }

    public static function myCart()
    {
    	if (Auth::check())
		{
			$cartLines = Cart::where('user_id', Auth::id())->get();
		} else {
			$cartLines = Cart::where('ip_address', Request::ip())->get();
		}

		return $cartLines;
    }

    public static function myCartCount()
    {
    	if (Auth::check())
		{
			$cartLines = Cart::where('user_id', Auth::id())->count();
		} else {
			$cartLines = Cart::where('ip_address', Request::ip())->count();
		}	

		return $cartLines;
    }

    public static function priceFromLines($lines = null)
    {
    	if (!$lines)
    	{
    		$lines = self::myCart();
    	}

    	$return['lines'] = 0;
		foreach ($lines as $line)
		{
			$return['lines'] += $line->price;
		}
		
		if ($return['lines']  >= 20)
		{
			$return['shipping']  = 0.00;
		} else {
			$return['shipping']  = 1.99;
		}

		$return['total'] = $return['lines'] + $return['shipping'];

        $return['lines'] = number_format($return['lines'], 2);
        $return['shipping'] = number_format($return['shipping'], 2);
        $return['total'] = number_format($return['total'], 2);

		return $return;
    }

    public function product()
    {
    	return $this->belongsTo('App\Product', 'product_id');
    }

    public function setQuantity($quantity)
    {
        if ($quantity == 0)
        {
            $this->delete();
            return false;
        }

    	$this->quantity_in_cart = $quantity;
    	$this->save();
    }

    public function user()
    {
    	return $this->belongsTo('App\User', 'user_id');
    }
}

app/Product.php
<?php

namespace App;

use App\ProductPicture;
use Auth;
use Illuminate\Database\Eloquent\Model;
use Image;
use Request;

class Product extends Model
{
    protected $fillable = ['game_id', 'slug', 'price', 'name', 'snippet', 'full_text', 'is_vatable', 'num_in_stock', 'supplier_url', 'supplier_product_id'];
    protected $table = 'products';

    public function addCategory($categoryID)
    {
        $this->categories()->attach($categoryID);
    }

    public function addPicture($requestPicture)
    {
        $array['product_id'] = $this->id;

        //Store the main image.
        $filename = $requestPicture->store('public/products/main');
        $array['url'] = 'products/main/'.basename($filename);

        //Store the thumbnail.
        $img = Image::make($requestPicture->getRealPath());
        $img->resize(250, 250);
        $thumbfilename = 'public/products/thumbnails/'.basename($filename);
        $thumbpath = storage_path('app/'.$thumbfilename);
        $img->save($thumbpath);
        $array['thumb_url'] = 'products/thumbnails/'.basename($filename);

        ProductPicture::create($array);
    }

    public function addToCart($quantity = 1)
    {
        if (Auth::check())
        {
            $array['user_id'] = Auth::id();
        }
        $array['ip_address'] = Request::ip();
        $array['product_id'] = $this->id;
        $cartLine = Cart::firstOrCreate($array);

        $cartLine->addQuantity($quantity);
    }

    public function carts()
    {
    	return $this->hasMany('App\Cart', 'product_id');
    }

    public function categories()
    {
        return $this->belongsToMany('App\ProductCategory', 'products_categories_link', 'product_id', 'category_id');
    } 

    public function competitorListings()
    {
        return $this->hasMany('App\CompetitorListing', 'product_id');
    }

    public function deleteCategory($categoryID)
    {
        $this->categories()->detach($categoryID);
    }

    public function getBoxAttribute()
    {
        return '<div class="col-3">'.$this->thumb_img.'<br />
            <a href="'.route('product.show', $this->slug).'">'.$this->name.'</a><br />
            '.$this->num_in_stock.' in stock</div>';
    }

    public function getFullTextNl2brAttribute()
    {
        return nl2br(e($this->full_text));
    }

    public function getMainImgAttribute()
    {
        $main = $this->thumbPicture();

        if (!$main) return '';

        return '<img src="'.$main->full_path.'">';
    }

    public function getMainImgPathAttribute()
    {
        $main = $this->thumbPicture();

        if (!$main) return '';

        return $main->full_path;
    }

    public function getPriceFormattedAttribute()
    {
        return '&pound;'.number_format($this->price / 100, 2);
    }

    public function getRestOfThumbsDivAttribute()
    {
        $return = '<div class="row">';

        foreach ($this->pictures as $p)
        {
            if (!($p->is_main))
            {
                $return .= '<div class="col-3"><a data-fancybox="gallery" href="'.$p->full_path.'"><img class="img-fluid" src="'.$p->thumb_path.'" /></a></div>';
            }
        }

        $return .= '</div>';

        return $return;
    }

    public function getThumbImgAttribute()
    {
        $thumb = $this->thumbPicture();

        if (!$thumb) return '';

        return '<img src="'.$thumb->thumb_path.'">';
    }

    public function invoiceLines()
    {
    	return $this->hasMany('App\InvoiceLine', 'product_id');
    }

    public function pictures()
    {
    	return $this->hasMany('App\ProductPicture', 'product_id');
    }

    //Returns the price in pence as integers. 
    public function priceArray()
    {
        $return['gross'] = $this->price;
        $return['vat']   = round(($this->price * $this->is_vatable / 6));
        $return['net']   = round(($return['gross'] - $return['vat']));

        return $return;
    }

    public function setMainPictureAsFirst()
    {
        if (!$this->pictures->first())
        {
            return false;
        }
        $this->pictures->first()->setMain(true);
    }

    public function thumbPicture()
    {
        return $this->pictures->sortByDesc('is_main')->first();
    }
}

resources/views/product/cart.blade.php
@extends('template')

@section('breadcrumbs')
    {{ Breadcrumbs::render('homeroute', 'Cart') }}
@endsection

@section('meta-description')
Purchase video games and video game accessories from Andach Game Rentals, great prices and availability!
@endsection

@section('title')
Purchase Video Games and Accessories | Andach Games
@endsection

@section('content')
	
	<h2>Cart (Step 1 of 4)</h2>

	@if (count($cartLines))

		{!! Form::open(['route' => 'product.cartpost', 'method' => 'POST']) !!}

		<div class="row">
			<div class="col-6">Product</div>
			<div class="col-2">Quantity</div>
			<div class="col-2">Price</div>
			<div class="col-2">Total</div>
		</div>

		@foreach ($cartLines as $line)
			{!! $line->box !!}
		@endforeach

		<div class="row">
			<div class="col-6"></div>
			<div class="col-2">{{ Form::submit('Update Quantities', ['class' => 'form-control btn btn-warning'])}}</div>
			<div class="col-2">Subtotal:</div>
			<div class="col-2">&pound;{{ $prices['lines'] }}</div>
		</div>
		<div class="row">
			<div class="col-8"></div>
			<div class="col-2">Delivery:</div>
			<div class="col-2">&pound;{{ $prices['shipping'] }}</div>
		</div>
		<div class="row">
			<div class="col-8"></div>
			<div class="col-2">Grand Total:</div>
			<div class="col-2">&pound;{{ $prices['total'] }}</div>
		</div>
		{!! Form::close() !!}

		<div class="row">
			<div class="col-8"></div>
			<div class="col-4"><a href="{{ route('product.cart2') }}">
				{{ Form::submit('>> Buy Now!', ['class' => 'form-control btn btn-success']) }}
			</a></div>
		</div>

	@else
		<div class="row">
			<div class="col-12">
				Your cart is empty. 
			</div>
		</div>
	@endif


@endsection

resources/views/product/cart2.blade.php
@extends('template')

@section('breadcrumbs')
    {{ Breadcrumbs::render('homeroute', 'Cart') }}
@endsection

@section('meta-description')
Address details for video games and video game accessories from Andach Game Rentals, great prices and availability!
@endsection

@section('title')
Address details for Video Games and Accessories | Andach Game Rentals | Video Games
@endsection

@section('content')
	
	<h2>Cart - Personal &amp; Delivery Info (Step 2 of 4)</h2>

	{!! Form::model(Auth::user(), ['route' => 'product.cart3', 'method', 'POST']) !!}

	@if (!Auth::check())
		<div class="alert alert-warning">
			You aren't logged in. If you log in, then all your orders will be saved in the same place and it'll be easier if there is any need to return any goods. 
		</div>
	@endif

	<div class="row">
		<div class="col-7">
			<div class="card">
				<div class="card-header">Your Details</div>
				<div class="card-body">
					<div class="row">
						{!! Form::label('name', 'Name:', ['class' => 'col-lg-2 control-label']) !!}
						<div class="col-lg-10">
					    	{!! Form::text('name', null, ['class' => 'form-control']) !!}
						</div>
					</div>
					<div class="row">
						{!! Form::label('email', 'Email:', ['class' => 'col-lg-2 control-label']) !!}
						<div class="col-lg-10">
					    	{!! Form::text('email', null, ['class' => 'form-control']) !!}
						</div>
					</div>
					<div class="row">
						{!! Form::label('phone', 'Phone:', ['class' => 'col-lg-2 control-label']) !!}
						<div class="col-lg-10">
					    	{!! Form::text('phone', null, ['class' => 'form-control']) !!}
						</div>
					</div>
					<div class="row">
						{!! Form::label('shipping_address1', 'Address 1:', ['class' => 'col-lg-2 control-label']) !!}
						<div class="col-lg-10">
					    	{!! Form::text('shipping_address1', null, ['class' => 'form-control']) !!}
						</div>
					</div>
					<div class="row">
						{!! Form::label('shipping_address2', 'Address 2:', ['class' => 'col-lg-2 control-label']) !!}
						<div class="col-lg-10">
					    	{!! Form::text('shipping_address2', null, ['class' => 'form-control']) !!}
						</div>
					</div>
					<div class="row">
						{!! Form::label('shipping_address3', 'Address 3:', ['class' => 'col-lg-2 control-label']) !!}
						<div class="col-lg-10">
					    	{!! Form::text('shipping_address3', null, ['class' => 'form-control']) !!}
						</div>
					</div>
					<div class="row">
						{!! Form::label('shipping_town', 'Town:', ['class' => 'col-lg-2 control-label']) !!}
						<div class="col-lg-10">
					    	{!! Form::text('shipping_town', null, ['class' => 'form-control']) !!}
						</div>
					</div>
					<div class="row">
						{!! Form::label('shipping_county', 'County:', ['class' => 'col-lg-2 control-label']) !!}
						<div class="col-lg-10">
					    	{!! Form::text('shipping_county', null, ['class' => 'form-control']) !!}
						</div>
					</div>
					<div class="row">
						{!! Form::label('shipping_postcode', 'Postcode:', ['class' => 'col-lg-2 control-label']) !!}
						<div class="col-lg-10">
					    	{!! Form::text('shipping_postcode', null, ['class' => 'form-control']) !!}
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-5">
			<div class="card">
				<div class="card-header">Order Summary</div>
				<div class="card-body">
					@foreach ($cartLines as $line)
						{!! $line->box_mini !!}
					@endforeach
					@if ($prices['shipping'] > 0)
						<div class="row">
				    		<div class="col-12 col-md-7">Shipping:</div>
				    		<div class="col-4 col-md-2"></div>
				    		<div class="col-8 col-md-3">&pound;{{ $prices['shipping'] }}</div>
			    		</div>
					@endif
				</div>
				<div class="card-footer">Total Price: &pound;{{ $prices['total'] }}</div>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-12">{{ Form::submit('>> Payment Details', ['class' => 'form-control btn btn-success']) }}</div>	
	</div>

	{!! Form::close() !!}

@endsection

resources/views/product/cart4.blade.php
@extends('template')

@section('breadcrumbs')
    {{ Breadcrumbs::render('homeroute', 'Cart') }}
@endsection

@section('meta-description')
Thankyou for your purchase from Andach Game Rentals!
@endsection

@section('title')
Thankyou for your Purchase | Andach Game Rentals | Video Games
@endsection

@section('content')
	
	<h2>Thankyou for your Purchase!</h2>

	<div class="row">
		<div class="col-12">Thankyou for buying from us.</div>
	</div>	

@endsection

resources/views/product/category.blade.php
@extends('template')

@section('breadcrumbs')
	{{ Breadcrumbs::render('category', $category) }}
@endsection

@section('content')
	
	<h2>{{ $category->name }}</h2>

	<div class="row">
		<ul class="nav nav-pills nav-justified">
			@foreach ($children as $child)
				<li class="nav-item">
					<a class="nav-link" href="{{ route('product.showcategory', $child['slug']) }}">{{ $child['name'] }}</a>
				</li>
			@endforeach	
		</ul>
	</div>

	<div class="row">
		@foreach ($category->products as $product)
			{!! $product->box !!}
		@endforeach	
	</div>

@endsection

resources/views/product/index.blade.php
@extends('template')

@section('content')
	
	<h2>Products Index</h2>

	<div class="row">
	@foreach ($products as $product)
		{!! $product->box !!}
	@endforeach
	</div>

@endsection

resources/views/product/show.blade.php
@extends('template')

@section('breadcrumbs')
	@foreach ($product->categories as $category)
    	{{ Breadcrumbs::render('product', $product, $category) }}
    @endforeach
@endsection

@section('content')
	
	<h2>{{ $product->name }}</h2>

	<div class="row">
		<div class="col-3">
			<a data-fancybox="gallery" href="{{ $product->main_img_path }}">{!! $product->thumb_img !!}</a>
			{!! $product->rest_of_thumbs_div !!}
			{{ Form::open(['route' => 'product.addtocart', 'method' => 'post']) }}
			
			{{ Form::hidden('product_id', $product->id) }}
			{{ Form::text('quantity', 1, ['class' => 'form-control']) }}
			{{ Form::submit('Add To Cart', ['class' => 'form-control btn btn-success']) }}

			{{ Form::close() }}
		</div>
		<div class="col-9">
			{!! $product->full_text_nl2br !!}
		</div>
	</div>

	@if (count($product->competitorListings))
		<h2>Our Competitor's Prices</h2>
		<div class="row">
			<div class="col-4">Competitor</div>
			<div class="col-2">New Price</div>
			<div class="col-2">Preowned Price</div>
			<div class="col-2">Buy Price</div>
			<div class="col-2">Voucher Price</div>
		</div>
		@foreach ($product->competitorListings as $l)
			<div class="row">
				<div class="col-4">{{ $l->competitor->name }}</div>
				<div class="col-2">{{ $l->latest_price_new_format }}</div>
				<div class="col-2">{{ $l->latest_price_preown_format }}</div>
				<div class="col-2">{{ $l->latest_price_buy_format }}</div>
				<div class="col-2">{{ $l->latest_price_voucher_format }}</div>
			</div>
		@endforeach
	@endif

	<!-- Root element of PhotoSwipe. Must have class pswp. -->
	<div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">

	    <!-- Background of PhotoSwipe. 
	         It's a separate element as animating opacity is faster than rgba(). -->
	    <div class="pswp__bg"></div>

	    <!-- Slides wrapper with overflow:hidden. -->
	    <div class="pswp__scroll-wrap">

	        <!-- Container that holds slides. 
	            PhotoSwipe keeps only 3 of them in the DOM to save memory.
	            Don't modify these 3 pswp__item elements, data is added later on. -->
	        <div class="pswp__container">
	            <div class="pswp__item"></div>
	            <div class="pswp__item"></div>
	            <div class="pswp__item"></div>
	        </div>

	        <!-- Default (PhotoSwipeUI_Default) interface on top of sliding area. Can be changed. -->
	        <div class="pswp__ui pswp__ui--hidden">

	            <div class="pswp__top-bar">

	                <!--  Controls are self-explanatory. Order can be changed. -->

	                <div class="pswp__counter"></div>

	                <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>

	                <button class="pswp__button pswp__button--share" title="Share"></button>

	                <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>

	                <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>

	                <!-- Preloader demo http://codepen.io/dimsemenov/pen/yyBWoR -->
	                <!-- element will get class pswp__preloader--active when preloader is running -->
	                <div class="pswp__preloader">
	                    <div class="pswp__preloader__icn">
	                      <div class="pswp__preloader__cut">
	                        <div class="pswp__preloader__donut"></div>
	                      </div>
	                    </div>
	                </div>
	            </div>

	            <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
	                <div class="pswp__share-tooltip"></div> 
	            </div>

	            <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)">
	            </button>

	            <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)">
	            </button>

	            <div class="pswp__caption">
	                <div class="pswp__caption__center"></div>
	            </div>

	        </div>

	    </div>

	</div>


@endsection

@section('javascript')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js"></script>

@endsection