routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/********************
* ROUTES - STATIC
********************/
Route::get('/', 'GameController@homepage')->name('home');

/********************
* ROUTES - PAGES
********************/
Route::get('page', 'PageController@index')->name('page.index');
Route::post('page', 'PageController@store')->name('page.store');
Route::get('page/create', 'PageController@create')->name('page.create');
Route::post('page/addcomment', 'PageController@addComment')->name('page.addcomment');
Route::put('page/{id}', 'PageController@update')->name('page.update');
Route::delete('page/{id}', 'PageController@destroy')->name('page.destroy');
Route::get('page/{slug}/edit', 'PageController@edit')->name('page.edit');

/********************
* ROUTES - GAMES
********************/
Route::get('game', 'GameController@index')->name('game.index');
Route::post('game', 'GameController@store')->name('game.store');
Route::get('game/create', 'GameController@create')->name('game.create');
//Because we might want to create a static page starting with "rent-", we have provision in the GameController@show method to push any unfound games to the appropriate PageController@show function. 
Route::get('rent-{game}', 'GameController@show')->name('game.show');
Route::get('achievements-{game}', 'GameController@achievements')->name('game.achievements');
Route::put('game/{game}', 'GameController@update')->name('game.update');
Route::delete('game/{game}', 'GameController@destroy')->name('game.destroy');
Route::get('game/{game}/edit', 'GameController@edit')->name('game.edit');
Route::post('game/addtowishlist', 'GameController@addToWishlist')->name('game.addtowishlist');
Route::post('game/deletefromwishlist', 'GameController@deleteFromWishlist')->name('game.deletefromwishlist');
Route::get('search-games', 'GameController@search')->name('game.search');

/********************
* ROUTES - PLAN
********************/
Route::get('plan', 'PlanController@index')->name('plan.index');
Route::post('plan-store', 'PlanController@store')->name('plan.store');
Route::get('plan/thanks', 'PlanController@thanks')->name('plan.thanks');
Route::get('plan/{slug}', 'PlanController@show')->name('plan.show');

/********************
* ROUTES - PRODUCTS
********************/
Route::get('cart', 'ProductController@cart')->name('product.cart');
Route::get('cart2', 'ProductController@cart2')->name('product.cart2');
Route::post('cart3', 'ProductController@cart3')->name('product.cart3');
Route::post('cart4', 'ProductController@cart4')->name('product.cart4');
Route::post('cart', 'ProductController@cartPost')->name('product.cartpost');
Route::get('product', 'ProductController@index')->name('product.index');
Route::post('product/addtocart', 'ProductController@addToCart')->name('product.addtocart');
Route::get('/product/convertcart', 'ProductController@convertCart')->name('product.convertcart');
Route::get('buy-{slug}', 'ProductController@show')->name('product.show');
Route::get('category-{slug}', 'ProductController@showcategory')->name('product.showcategory');

/********************
* ROUTES - USER
********************/
Route::get('user/account', 'UserController@account')->name('user.account');
Route::post('user/accountupdate', 'UserController@accountUpdate')->name('user.accountupdate');
Route::get('user/agelimit', 'UserController@ageLimit')->name('user.agelimit');
Route::get('user/agelimitconfirm/{hash}', 'UserController@ageLimitConfirm')->name('user.agelimitconfirm');
Route::post('user/agelimitupdate', 'UserController@ageLimitUpdate')->name('user.agelimitupdate');
Route::get('user/edit', 'UserController@edit')->name('user.edit');
Route::get('user/history', 'UserController@history')->name('user.history');
Route::get('user/invoice/{id}', 'UserController@invoiceShow')->name('user.invoiceshow');
Route::get('user/invoices', 'UserController@invoiceList')->name('user.invoicelist');
Route::get('user/subscription', 'UserController@subscription')->name('user.subscription');
Route::post('user/subscription/cancel', 'UserController@cancelSubscription')->name('user.cancelsubscription');
Route::post('user/subscription/resume', 'UserController@resumeSubscription')->name('user.resumesubscription');
Route::put('user/update', 'UserController@update')->name('user.update');
Route::post('user/register', 'UserController@registerPost')->name('user.register');
Route::get('user/registeraddress', 'UserController@registerAddress')->name('user.registeraddress');

/********************
* ROUTES - ADMIN
********************/
Route::get('admin/', 'AdminController@admin')->name('admin.admin');
Route::post('admin/assignment-run', 'AdminController@assignmentRun')->name('admin.assignmentrun');
Route::get('admin/competitors', 'AdminController@competitors')->name('admin.competitors');
Route::post('admin/competitors-post', 'AdminController@competitorsPost')->name('admin.competitorspost');
Route::post('admin/confirm-assignments', 'AdminController@confirmassignments')->name('admin.confirmassignments');
Route::get('admin/games/{numberofdays?}/{limit?}', 'AdminController@gameIndex')->name('admin.gameindex');
Route::post('admin/games-post', 'AdminController@gameIndexPost')->name('admin.gameindexpost');
Route::get('admin/igdb/{name}', 'AdminController@IGDBSearch')->name('admin.igdbsearch');
Route::get('admin/printdeliverynote/{id}', 'AdminController@printDeliveryNote')->name('admin.printdeliverynote');
Route::get('admin/product/create/', 'AdminController@productCreate')->name('admin.productcreate');
Route::get('admin/product/edit/{id}', 'AdminController@productEdit')->name('admin.productedit');
Route::get('admin/product/', 'AdminController@productIndex')->name('admin.productindex');
Route::post('admin/product/', 'AdminController@productStore')->name('admin.productstore');
Route::put('admin/product/', 'AdminController@productUpdate')->name('admin.productupdate');
Route::get('admin/rentals', 'AdminController@rentals')->name('admin.rentals');
Route::post('admin/rentals-update', 'AdminController@rentalsUpdate')->name('admin.rentalsupdate');
Route::get('admin/send-games', 'AdminController@sendGames')->name('admin.sendgames');
Route::get('admin/stock/', 'AdminController@stockIndex')->name('admin.stockindex');
Route::get('admin/stock/{id}', 'AdminController@stock')->name('admin.stock');
Route::post('admin/stock-update', 'AdminController@stockUpdate')->name('admin.stockupdate');
Route::get('admin/upload-games', 'AdminController@uploadGames')->name('admin.uploadgames');
Route::post('admin/upload-games-post', 'AdminController@uploadGamesPost')->name('admin.uploadgamespost');
Route::get('admin/upload-stock', 'AdminController@uploadStock')->name('admin.uploadstock');
Route::post('admin/upload-stock-post', 'AdminController@uploadStockPost')->name('admin.uploadstockpost');
Route::any('admin/users', 'AdminController@users')->name('admin.users');

Route::get('admin/testmail', 'AdminController@testMail')->name('admin.testmail');

/********************
* ROUTES - CONTACT
********************/
Route::get('contact', 'ContactController@create')->name('contact.create');
Route::get('contact/index', 'ContactController@index')->name('contact.index');
Route::get('contact/attachment/{slug}', 'ContactController@attachment')->name('contact.attachment');
Route::post('contact/send', 'ContactController@store')->name('contact.store');
Route::get('contact/show/{id}', 'ContactController@show')->name('contact.show');
Route::post('contact/update/', 'ContactController@update')->name('contact.update');

/********************
* ROUTES - OTHER
********************/
Route::get('braintree/token', 'BraintreeTokenController@token');
Route::post('braintree/webhook', 'WebhookController@handleWebhook');

Auth::routes();
Route::get('log-out', 'Auth\LoginController@logout')->name('log-out');

Route::get('login/{provider}', 'Auth\SocialAccountController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\SocialAccountController@handleProviderCallback');

Route::get('sitemap', 'SitemapController@index')->name('sitemap');

Route::get('{slug}', 'PageController@show')->where('slug', '(.*)')->name('page.show');

app/Cart.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Auth;
use Form;
use Request;

class Cart extends Model
{
	protected $fillable = ['product_id', 'user_id', 'ip_address', 'quantity_in_cart'];
    protected $table = 'cart';

    public function addQuantity($quantity)
    {
    	$this->quantity_in_cart = $this->quantity_in_cart + $quantity;
    	$this->save();
    }

    //For use when a user logs in to convert any lines they might have in their cart and add them to any lines they have against their user. 
    public static function convertCartToUser()
    {
        if (!Auth::check()) return false;

        $cartLinesIP   = Cart::where('ip_address', Request::ip())->get();
        $cartLinesUser = Cart::where('user_id', Auth::id())->get();

        foreach ($cartLinesUser as $line)
        {
            if ($ipLine = $cartLinesIP->where('product_id', $line->product_id)->first())
            {
                $line->quantity_in_cart = $line->quantity_in_cart + $ipLine->quantity_in_cart;
                $line->save();
                $ipLine->delete();
            }
        }

        Cart::where('ip_address', Request::ip())->update(['user_id' => Auth::id(), 'ip_address' => '']);
    }

    public static function empty()
    {
        if (Auth::check())
        {
            self::where('user_id', Auth::id())->delete();
        }
        self::where('ip_address', Request::ip())->delete();
    }

    public function getBoxAttribute()
    {
    	return '<div class="row">
    		<div class="col-6"><a href="'.route('product.show', $this->product->slug).'">'.$this->product->name.'</a></div>
    		<div class="col-2">'.
    			Form::text('cartQuantity['.$this->id.']', $this->quantity_in_cart, ['class' => 'form-control'])
    		.'</div>
    		<div class="col-2">'.$this->product->price_formatted.'</div>
    		<div class="col-2">'.$this->price_formatted.'</div>
    		</div>';
    }

    public function getBoxMiniAttribute()
    {
    	return '<div class="row">
    		<div class="col-12 col-md-7"><a href="'.route('product.show', $this->product->slug).'">'.$this->product->name.'</a></div>
    		<div class="col-4 col-md-2">'.$this->quantity_in_cart.'</div>
    		<div class="col-8 col-md-3">'.$this->price_formatted.'</div>
    		</div>';
    }

    public function getPriceAttribute()
    {
    	return $this->quantity_in_cart * $this->product->price / 100;
    }

    public function getPriceFormattedAttribute()
    {
    	return '&pound;'.number_format($this->price, 2);
    }

    //Returns the array needed to convert this into an invoice line.
    public function invoiceLineArray()
    {
        $priceArray = $this->product->priceArray();

        $return['product_id'] = $this->product_id;
        $return['quantity_invoiced'] = $this->quantity_in_cart;
        $return['net'] = $this->quantity_in_cart * $priceArray['net'];
        $return['vat'] = $this->quantity_in_cart * $priceArray['vat'];
        $return['gross'] = $this->quantity_in_cart * $priceArray['gross'];
        $return['net_per_item'] = $priceArray['net'];
        $return['vat_per_item'] = $priceArray['vat'];
        $return['gross_per_item'] = $priceArray['gross'];
        
        return $return;
    }

    public static function myCart()
    {
    	if (Auth::check())
		{
			$cartLines = Cart::where('user_id', Auth::id())->get();
		} else {
			$cartLines = Cart::where('ip_address', Request::ip())->get();
		}

		return $cartLines;
    }

    public static function myCartCount()
    {
    	if (Auth::check())
		{
			$cartLines = Cart::where('user_id', Auth::id())->count();
		} else {
			$cartLines = Cart::where('ip_address', Request::ip())->count();
		}	

		return $cartLines;
    }

    public static function priceFromLines($lines = null)
    {
    	if (!$lines)
    	{
    		$lines = self::myCart();
    	}

    	$return['lines'] = 0;
		foreach ($lines as $line)
		{
			$return['lines'] += $line->price;
		}
		
		if ($return['lines']  >= 20)
		{
			$return['shipping']  = 0.00;
		} else {
			$return['shipping']  = 1.99;
		}

		$return['total'] = $return['lines'] + $return['shipping'];

        $return['lines'] = number_format($return['lines'], 2);
        $return['shipping'] = number_format($return['shipping'], 2);
        $return['total'] = number_format($return['total'], 2);

		return $return;
    }

    public function product()
    {
    	return $this->belongsTo('App\Product', 'product_id');
    }

    public function setQuantity($quantity)
    {
        if ($quantity == 0)
        {
            $this->delete();
            return false;
        }

    	$this->quantity_in_cart = $quantity;
    	$this->save();
    }

    public function user()
    {
    	return $this->belongsTo('App\User', 'user_id');
    }
}

app/Page.php
<?php

namespace App;

use Auth;
use Illuminate\Database\Eloquent\Model;

class Page extends Model
{
	protected $fillable = ['slug', 'game_id', 'name', 'h1', 'html_title', 'meta_description', 'body', 'date_published', 'author_id', 'is_commentable'];
    protected $table = 'pages';

    public function author()
    {
    	return $this->belongsTo('App\User', 'author_id');
    }
    
    public function canComment()
    {
        return $this->is_commentable && Auth::check();
    }
    
    public function comments()
    {
        return $this->hasMany('App\PageComment', 'page_id');
    }
    
    public function game()
    {
        return $this->belongsTo('App\Game', 'game_id');
    }

    public function getAuthorNameAttribute()
    {
    	if ($this->author)
    	{
    		return $this->author->name;
    	}

    	return '';
    }

    //Replaces certain elements with bootstrap classes. 
    public function getBootstrappedBodyAttribute()
    {
        $return = $this->body;

        $return = str_replace('<blockquote>', '<blockquote class="blockquote">', $return);
        $return = str_replace('type="button"', 'type="button" class="form-control btn btn-success"', $return);

        return $return;
    }
}

resources/views/page/form.blade.php
@extends('template')

@section('content')
	@include('admin.menu')
	@if (isset($page))
		{!! Form::model($page, ['route' => ['page.update', $page->id], 'files' => true, 'method' => 'PUT']) !!}
	@else
		{!! Form::open(['route' => 'page.store', 'files' => true]) !!}
	@endif

	<h2>Create or Edit Page</h2>
	<div class="row">
		{!! Form::label('slug', 'Slug:', ['class' => 'col-lg-2 control-label']) !!}
		<div class="col-lg-10">
	    	{!! Form::text('slug', null, ['class' => 'form-control']) !!}
		</div>
	</div>
	<div class="row">
		{!! Form::label('name', 'Name:', ['class' => 'col-lg-2 control-label']) !!}
		<div class="col-lg-10">
	    	{!! Form::text('name', null, ['class' => 'form-control']) !!}
		</div>
	</div>

	<div class="row">
		{!! Form::label('h1', 'H1:', ['class' => 'col-lg-2 control-label']) !!}
		<div class="col-lg-10">
	    	{!! Form::text('h1', null, ['class' => 'form-control']) !!}
		</div>
	</div>

	<div class="row">
		{!! Form::label('html_title', 'HTML Title:', ['class' => 'col-lg-2 control-label']) !!}
		<div class="col-lg-10">
	    	{!! Form::text('html_title', null, ['class' => 'form-control']) !!}
		</div>
	</div>

	<p id="titleCharacters"></p>

	<div class="row">
		{!! Form::label('meta_description', 'Meta Description:', ['class' => 'col-lg-2 control-label']) !!}
		<div class="col-lg-10">
	    	{!! Form::textarea('meta_description', null, ['class' => 'form-control']) !!}
		</div>
	</div>

	<p id="descCharacters"></p>

	<div class="row">
		{!! Form::label('body', 'Body:', ['class' => 'col-lg-2 control-label']) !!}
		<div class="col-lg-10">
	    	{!! Form::textarea('body', null, ['class' => 'form-control']) !!}
		</div>
	</div>

	<div class="row">
		{!! Form::label('date_published', 'Date Published:', ['class' => 'col-lg-2 control-label']) !!}
		<div class="col-lg-10">
	    	{!! Form::date('date_published', null, ['class' => 'form-control']) !!}
		</div>
	</div>

	<div class="row">
		{!! Form::label('game_id', 'Game (optional)', ['class' => 'col-lg-2 control-label']) !!}
		<div class="col-lg-10">
	    	{!! Form::select('game_id', $games, null, ['class' => 'form-control', 'placeholder' => '-- please select game --']) !!}
		</div>
	</div>

	<div class="row">
		{!! Form::label('is_commentable', 'Is Commentable?', ['class' => 'col-lg-2 control-label']) !!}
		<div class="col-lg-10">
	    	{!! Form::checkbox('is_commentable', 1, null, ['class' => 'form-control']) !!}
		</div>
	</div>

	<div class="row">
		<div class="col-lg-12">
			@if (isset($page))
				{{ Form::submit('Edit this Page', ['class' => 'form-control btn btn-success']) }}
			@else
				{{ Form::submit('Add this Page', ['class' => 'form-control btn btn-success']) }}
			@endif
			
		</div>
	</div>

	{!! Form::close() !!}

@endsection

@section('javascript')
<script src="//cdn.ckeditor.com/4.9.1/full-all/ckeditor.js"></script>
<script>
  var options = {
    filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
    filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=',
    filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
    filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token='
  };

  CKEDITOR.replace('body', options);

	document.getElementById('html_title').oninput= function(e)
	{
	    document.getElementById('titleCharacters').innerHTML = '<b>' + (this.value.length) + ' characters (60 max)</b>';
	};

	document.getElementById('meta_description').oninput= function(e)
	{
	    document.getElementById('descCharacters').innerHTML = '<b>' + (this.value.length) + ' characters (300 max)</b>';
	};
</script>
@endsection

resources/views/page/index.blade.php
@extends('template')

@section('content')
	@include('admin.menu')
	
	<h2>Pages Index</h2>

	<p><a href="{{ route('page.create') }}">Create a Page</a></p>
	<div class="row">
		<div class="col-1">ID</div>
		<div class="col-3">Slug</div>
		<div class="col-3">H1</div>
		<div class="col-5">User</div>
	</div>

	@foreach ($pages as $page)

		<div class="row">
			<div class="col-1">{{ $page->id }}</div>
			<div class="col-3"><a href="{{ route('page.edit', $page->id) }}">{{ $page->slug }}</a></div>
			<div class="col-3"><a href="{{ route('page.show', $page->slug) }}">{{ $page->h1 }}</a></div>
			<div class="col-5">{{ $page->author_name }}</div>
		</div>

	@endforeach

@endsection

resources/views/page/show.blade.php
@extends('template')

@section('google-analytics')
	gtag('set', {'content_group1': 'Static Pages'}); 
@endsection

@section('breadcrumbs')
    {{ Breadcrumbs::render('homeroute', $page->name) }}
@endsection

@section('h1'){{ $page->h1 }}@endsection

@section('meta-description'){{ $page->meta_description }}@endsection

@section('title'){{ $page->html_title }}@endsection

@section('microdata')
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Article",
  "author": {
    "@type": "Organization",
    "name": "Andach Games Ltd"
  },
  "publisher": {
    "@type": "Organization",
    "name": "Andach Games Ltd",
    "logo": {
      "@type": "ImageObject",
      "url": "https://andachgames.co.uk/images/template/andach-rental-logo.png",
      "width": 98,
      "height": 60
    }
  },
  "mainEntityOfPage": {
   "@type": "WebPage",
   "@id": "{{ url()->current() }}"
  },
  "datePublished": "{{ $page->created_at }}",
  "dateModified": "{{ $page->updated_at }}",
  "headline": "{{ $page->h1 }}",
  "image": {
    "@type": "ImageObject",
    "url": "https://andachgames.co.uk/images/template/andach-rental-logo.png",
    "width": 98,
    "height": 60
  }
}
</script>
@endsection

@section('content')
	<div class="row">
		<div class="col-12">
			{!! $page->bootstrapped_body !!}
		</div>
	</div>

    @if (count($page->comments))
        <h2>{{ count($page->comments) }} Comment(s) on this Page</h2>
        @foreach ($page->comments as $comment)
            {!! $comment->box !!}
        @endforeach
    @endif

    @if ($page->canComment())
        {{ Form::open(['route' => 'page.addcomment', 'method' => 'post']) }}
        <h2>Add a Comment</h2>
        <p>{{ Form::hidden('id', $page->id) }}</p>
        <p>{{ Form::textarea('comment', null, ['class' => 'form-control']) }}</p>
        <p>{{ Form::submit('Add Comment', ['class' => 'form-control btn btn-success']) }}</p>
        {{ Form::close() }}
    @endif
@endsection