routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/********************
* ROUTES - STATIC
********************/
Route::get('/', 'GameController@homepage')->name('home');

/********************
* ROUTES - PAGES
********************/
Route::get('page', 'PageController@index')->name('page.index');
Route::post('page', 'PageController@store')->name('page.store');
Route::get('page/create', 'PageController@create')->name('page.create');
Route::post('page/addcomment', 'PageController@addComment')->name('page.addcomment');
Route::put('page/{id}', 'PageController@update')->name('page.update');
Route::delete('page/{id}', 'PageController@destroy')->name('page.destroy');
Route::get('page/{slug}/edit', 'PageController@edit')->name('page.edit');

/********************
* ROUTES - GAMES
********************/
Route::get('game', 'GameController@index')->name('game.index');
Route::post('game', 'GameController@store')->name('game.store');
Route::get('game/create', 'GameController@create')->name('game.create');
//Because we might want to create a static page starting with "rent-", we have provision in the GameController@show method to push any unfound games to the appropriate PageController@show function. 
Route::get('rent-{game}', 'GameController@show')->name('game.show');
Route::get('achievements-{game}', 'GameController@achievements')->name('game.achievements');
Route::put('game/{game}', 'GameController@update')->name('game.update');
Route::delete('game/{game}', 'GameController@destroy')->name('game.destroy');
Route::get('game/{game}/edit', 'GameController@edit')->name('game.edit');
Route::post('game/addtowishlist', 'GameController@addToWishlist')->name('game.addtowishlist');
Route::post('game/deletefromwishlist', 'GameController@deleteFromWishlist')->name('game.deletefromwishlist');
Route::get('search-games', 'GameController@search')->name('game.search');

/********************
* ROUTES - PLAN
********************/
Route::get('plan', 'PlanController@index')->name('plan.index');
Route::post('plan-store', 'PlanController@store')->name('plan.store');
Route::get('plan/thanks', 'PlanController@thanks')->name('plan.thanks');
Route::get('plan/{slug}', 'PlanController@show')->name('plan.show');

/********************
* ROUTES - PRODUCTS
********************/
Route::get('cart', 'ProductController@cart')->name('product.cart');
Route::get('cart2', 'ProductController@cart2')->name('product.cart2');
Route::post('cart3', 'ProductController@cart3')->name('product.cart3');
Route::post('cart4', 'ProductController@cart4')->name('product.cart4');
Route::post('cart', 'ProductController@cartPost')->name('product.cartpost');
Route::get('product', 'ProductController@index')->name('product.index');
Route::post('product/addtocart', 'ProductController@addToCart')->name('product.addtocart');
Route::get('/product/convertcart', 'ProductController@convertCart')->name('product.convertcart');
Route::get('buy-{slug}', 'ProductController@show')->name('product.show');
Route::get('category-{slug}', 'ProductController@showcategory')->name('product.showcategory');

/********************
* ROUTES - USER
********************/
Route::get('user/account', 'UserController@account')->name('user.account');
Route::post('user/accountupdate', 'UserController@accountUpdate')->name('user.accountupdate');
Route::get('user/agelimit', 'UserController@ageLimit')->name('user.agelimit');
Route::get('user/agelimitconfirm/{hash}', 'UserController@ageLimitConfirm')->name('user.agelimitconfirm');
Route::post('user/agelimitupdate', 'UserController@ageLimitUpdate')->name('user.agelimitupdate');
Route::get('user/edit', 'UserController@edit')->name('user.edit');
Route::get('user/history', 'UserController@history')->name('user.history');
Route::get('user/invoice/{id}', 'UserController@invoiceShow')->name('user.invoiceshow');
Route::get('user/invoices', 'UserController@invoiceList')->name('user.invoicelist');
Route::get('user/subscription', 'UserController@subscription')->name('user.subscription');
Route::post('user/subscription/cancel', 'UserController@cancelSubscription')->name('user.cancelsubscription');
Route::post('user/subscription/resume', 'UserController@resumeSubscription')->name('user.resumesubscription');
Route::put('user/update', 'UserController@update')->name('user.update');
Route::post('user/register', 'UserController@registerPost')->name('user.register');
Route::get('user/registeraddress', 'UserController@registerAddress')->name('user.registeraddress');

/********************
* ROUTES - ADMIN
********************/
Route::get('admin/', 'AdminController@admin')->name('admin.admin');
Route::post('admin/assignment-run', 'AdminController@assignmentRun')->name('admin.assignmentrun');
Route::get('admin/competitors', 'AdminController@competitors')->name('admin.competitors');
Route::post('admin/competitors-post', 'AdminController@competitorsPost')->name('admin.competitorspost');
Route::post('admin/confirm-assignments', 'AdminController@confirmassignments')->name('admin.confirmassignments');
Route::get('admin/games/{numberofdays?}/{limit?}', 'AdminController@gameIndex')->name('admin.gameindex');
Route::post('admin/games-post', 'AdminController@gameIndexPost')->name('admin.gameindexpost');
Route::get('admin/igdb/{name}', 'AdminController@IGDBSearch')->name('admin.igdbsearch');
Route::get('admin/printdeliverynote/{id}', 'AdminController@printDeliveryNote')->name('admin.printdeliverynote');
Route::get('admin/product/create/', 'AdminController@productCreate')->name('admin.productcreate');
Route::get('admin/product/edit/{id}', 'AdminController@productEdit')->name('admin.productedit');
Route::get('admin/product/', 'AdminController@productIndex')->name('admin.productindex');
Route::post('admin/product/', 'AdminController@productStore')->name('admin.productstore');
Route::put('admin/product/', 'AdminController@productUpdate')->name('admin.productupdate');
Route::get('admin/rentals', 'AdminController@rentals')->name('admin.rentals');
Route::post('admin/rentals-update', 'AdminController@rentalsUpdate')->name('admin.rentalsupdate');
Route::get('admin/send-games', 'AdminController@sendGames')->name('admin.sendgames');
Route::get('admin/stock/', 'AdminController@stockIndex')->name('admin.stockindex');
Route::get('admin/stock/{id}', 'AdminController@stock')->name('admin.stock');
Route::post('admin/stock-update', 'AdminController@stockUpdate')->name('admin.stockupdate');
Route::get('admin/upload-games', 'AdminController@uploadGames')->name('admin.uploadgames');
Route::post('admin/upload-games-post', 'AdminController@uploadGamesPost')->name('admin.uploadgamespost');
Route::get('admin/upload-stock', 'AdminController@uploadStock')->name('admin.uploadstock');
Route::post('admin/upload-stock-post', 'AdminController@uploadStockPost')->name('admin.uploadstockpost');
Route::any('admin/users', 'AdminController@users')->name('admin.users');

Route::get('admin/testmail', 'AdminController@testMail')->name('admin.testmail');

/********************
* ROUTES - CONTACT
********************/
Route::get('contact', 'ContactController@create')->name('contact.create');
Route::get('contact/index', 'ContactController@index')->name('contact.index');
Route::get('contact/attachment/{slug}', 'ContactController@attachment')->name('contact.attachment');
Route::post('contact/send', 'ContactController@store')->name('contact.store');
Route::get('contact/show/{id}', 'ContactController@show')->name('contact.show');
Route::post('contact/update/', 'ContactController@update')->name('contact.update');

/********************
* ROUTES - OTHER
********************/
Route::get('braintree/token', 'BraintreeTokenController@token');
Route::post('braintree/webhook', 'WebhookController@handleWebhook');

Auth::routes();
Route::get('log-out', 'Auth\LoginController@logout')->name('log-out');

Route::get('login/{provider}', 'Auth\SocialAccountController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\SocialAccountController@handleProviderCallback');

Route::get('sitemap', 'SitemapController@index')->name('sitemap');

Route::get('{slug}', 'PageController@show')->where('slug', '(.*)')->name('page.show');

app/Invoice.php
<?php

namespace App;

use App\Cart;
use App\InvoiceLine;
use Illuminate\Database\Eloquent\Model;

class Invoice extends Model
{
	protected $fillable = ['user_id', 'name', 'email', 'phone', 'date_of_invoice', 'shipping_address1', 'shipping_address2', 'shipping_address3', 'shipping_town', 'shipping_county', 'shipping_postcode', 'billing_address1', 'billing_address2', 'billing_address3', 'billing_town', 'billing_county', 'billing_postcode'];
    protected $table = 'invoices';

    public function calculateTotals()
    {
        $this->lines_net   = $this->lines->sum('net');
        $this->lines_vat   = $this->lines->sum('vat');
        $this->lines_gross = $this->lines->sum('gross');
        $this->net   = $this->lines_net + $this->shipping_net;
        $this->vat   = $this->lines_vat + $this->shipping_vat;
        $this->gross = $this->lines_gross + $this->shipping_gross;
    }

    public function finalise()
    {
        if ($this->date_of_finalising) return false;

        $this->calculateTotals();

        if (!$this->date_of_invoice)
        {
            $this->date_of_invoice = date('Y-m-d');
        }

        $this->date_of_finalising = date('Y-m-d');

        $this->save();
    }

    public function getFormattedBillingAddressAttribute()
    {
        $array[] = $this->billing_address1;
        $array[] = $this->billing_address2;
        $array[] = $this->billing_address3;
        $array[] = $this->billing_town;
        $array[] = $this->billing_county;
        $array[] = $this->billing_postcode;

        return implode('<br />', array_filter($array));
    }

    public function getFormattedShippingAddressAttribute()
    {
        $array[] = $this->shipping_address1;
        $array[] = $this->shipping_address2;
        $array[] = $this->shipping_address3;
        $array[] = $this->shipping_town;
        $array[] = $this->shipping_county;
        $array[] = $this->shipping_postcode;

        return implode('<br />', array_filter($array));
    }

    public function getFormattedUserInfoAttribute()
    {
        $array[] = $this->name;
        $array[] = $this->email;
        $array[] = $this->phone;
        $array[] = $this->date_of_invoice;

        return implode('<br />', array_filter($array));
    }

    public function getFormattedValue($name)
    {
        return '&pound;'.number_format($this->$name / 100, 2);
    }

    public function importCart()
    {
        $cartLines = Cart::myCart();

        foreach ($cartLines as $cartLine)
        {
            $invoiceLine = new InvoiceLine;
            $invoiceLine->fill($cartLine->invoiceLineArray());
            $invoiceLine->invoice_id = $this->id;
            $invoiceLine->save();
        }
    }

    public function lines()
    {
    	return $this->hasMany('App\InvoiceLine', 'invoice_id');
    }

    public static function nextInvoiceID()
    {
        return Invoice::max('id') + 1;
    }

    public function setShippingGrossInPounds($price)
    {
        $this->shipping_gross = round($price * 100);
        $this->shipping_vat   = round($this->shipping_gross / 6);
        $this->shipping_net   = $this->shipping_gross - $this->shipping_vat;
        $this->save();
    }

    public function user()
    {
    	return $this->belongsTo('App\User', 'user_id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Mail\SubscriptionCancel;
use App\Mail\SubscriptionResume;
use App\Invoice;
use App\Rental;
use App\User;
use App\Wishlist;
use Auth;
use Illuminate\Http\Request;
use Mail;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function account()
    {
        $user = Auth::user();

        return view('user.account', ['user' => $user]);
    }

    public function accountUpdate(Request $request)
    {
        $user = Auth::user();

        $order = array_flip($request->order);

        foreach ($user->wishlists as $wish)
        {
            $wish->order = $order[$wish->game_id];
            $wish->save();
        }

        if (isset($request->delete))
        {
            foreach ($request->delete as $gameID)
            {
                $wishlist = Wishlist::where('user_id', $user->id)->where('game_id', $gameID)->first();
                $wishlist->delete();
            }
        }

        $request->session()->flash('success', 'Your wishlist has been updated!');

        return redirect()->route('user.account');
    }
    
    public function ageLimit()
    {
        $user = Auth::user();

        return view('user.agelimit', ['user' => $user]);
    }
    
    public function ageLimitConfirm($hash)
    {
        $user = User::where('maximum_age_hash', $hash)->first();
        
        if (!$user->count())
        {
            session()->flash('danger', 'Your code was not recognised');
            return redirect()->route('home');
        }
        
        if ($user->confirmAgeLimit($hash))
        {
            session()->flash('success', 'Your new age limit has been confirmed');
        } else {
            session()->flash('danger', 'Your new age limit has not been set. It\'s most likely expired. Please head into your <a href="'.route('user.agelimit').'">user area</a> and get a new email sent to you.');
        }
        
        return redirect()->route('home');
    }
    
    public function ageLimitUpdate(Request $request)
    {
        $user = Auth::user();

        $user->ageLimitToConfirm($request->age);
        session()->flash('success', 'Please click the link in your email to confirm your new age limit.');
        
        return redirect()->route('user.agelimit');
    }

    public function cancelSubscription(Request $request)
    {
        if($request->confirm)
        {
            Auth::user()->cancelSubscription();
            $request->session()->flash('success', 'You have cancelled your subscription.');

            $user = Auth::user();
            Mail::to($user)->send(new SubscriptionCancel($user->currentSubscription()->ends_at));

            return view('user.subscription', ['user' => $user]);
        }

        return view('user.cancelsubscription');
    }

    public function edit()
    {
        $user = Auth::user();

        return view('user.form', ['user' => $user]);
    }

    public function history()
    {
        $rentals = Rental::where('user_id', Auth::id())->whereNotNull('date_of_delivery')->get();

        return view('user.history', ['rentals' => $rentals]);
    }

    public function invoiceList()
    {
        $invoices = Invoice::where('user_id', Auth::id())->get();

        return view('user.invoicelist', ['invoices' => $invoices]);
    }

    public function invoiceShow($id)
    {
        $invoice = Invoice::where('user_id', Auth::id())->where('id', $id)->first();

        return view('user.invoiceshow', ['invoice' => $invoice]);
    }

    public function registerAddress()
    {
        $user = Auth::user();

        return view('user.registeraddress', ['user' => $user]);
    }

    public function registerPost(Request $request)
    {
        $request->validate([
            'shipping_address1' => 'required',
            'shipping_postcode' => 'required',
        ]);

        $user = User::find(Auth::id());
        $user->update($request->all());
        $request->session()->flash('success', 'You have successfully added your address details. Now choose your plan. ');
        return redirect()->route('plan.index');
    }

    public function resumeSubscription(Request $request)
    {
        Auth::user()->resumeSubscription();

        $request->session()->flash('success', 'Your subscription has been set to resume.');
        $user = Auth::user();
        Mail::to($user)->send(new SubscriptionResume());

        return view('user.subscription', ['user' => $user]);
    }

    public function subscription()
    {
        $user = Auth::user();

        return view('user.subscription', ['user' => $user]);
    }

    public function update(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'email' => 'required',
            'shipping_address1' => 'required',
            'shipping_postcode' => 'required',
        ]);
                
        $user = Auth::user();

        $user->update($request->all());

        if (!$request->marketing_subscribe)
        {
            $user->marketing_subscribe = 0;
            $user->save();
        }

        $request->session()->flash('success', 'You have successfully changed your account details.');

        return redirect()->route('user.edit');
    }
}

resources/views/user/account.blade.php
@extends('template')

@section('content')
	@include('user.menu')
	
	<h2>My Current List</h2>
	{!! Form::open(['route' => 'user.accountupdate']) !!}

    <!--
	<div class="row">
		<div class="col-2">Boxart</div>
		<div class="col-3">Game</div>
        <div class="col-6">Number in Stock</div>
        <div clas="col-1">Delete?</div>
	</div>
    -->

	<div id="left-defaults" class="dragula-container">
		@foreach ($user->wishlistGames as $game)
			{!! $game->wishlist !!}
		@endforeach
	</div>
    
    <div class="row">
        <div class="col-2">{{ Form::submit('Delete from List', ['class' => 'form-control btn btn-danger', 'name' => 'btnDelete']) }}</div>
        <div class="col-6"></div>
        <div class="col-4">{{ Form::submit('Update List Order', ['class' => 'form-control btn btn-success', 'name' => 'btnUpdate']) }}</div>
    </div>
	{!! Form::close() !!}

@endsection

@section('javascript')
    <script>
    dragula([document.getElementById('left-defaults')]);
    </script>
@endsection

resources/views/user/agelimit.blade.php
@extends('template')

@section('content')
	@include('user.menu')
	
	<h2>Set an Age Limit</h2>
	{!! Form::open(['route' => 'user.agelimitupdate']) !!}

	<div class="row">
		<div class="col-12">You can set an age limit for your account. 
            This means only games of a certain PEGI age rating can be added to a wishlist. 
            You may want this feature to be enabled if you are subscribing for your child. 
            You can share your account with your child, and they can't change the age limit without your email. 
            When you select a new age limit, an email will be sent to you with a link to click - you'll need to do this within 24 hours. 
        </div>
        <div class="col-12">{!! $user->age_limit_box !!}</div>
        <div class="col-2">New Age Limit:</div>
        <div class="col-10">
            <select name="age" class="form-control">
                <option value="3">3</option>
                <option value="7">7</option>
                <option value="12">12</option>
                <option value="16">16</option>
                <option value="">18 (remove age limit)</option>
            </select>
        </div>
        <div class="col-12">
            {{ Form::submit('Update Age Limit', ['class' => 'form-control btn btn-success']) }}
        </div>
	</div>
        
	{!! Form::close() !!}

@endsection

resources/views/user/cancelsubscription.blade.php
@extends('template')

@section('content')
	@include('user.menu')
	
	<h2>Cancel Subscription</h2>
	<p>Are you sure you want to cancel your subscription?</p>
	{{ Form::open(['route' => 'user.cancelsubscription', 'method' => 'POST']) }}
	<div class="row">
		<div class="col-12">
			{{ Form::hidden('confirm', 1) }}
			{{ Form::submit('Yes, I am sure. Cancel my Subscription', ['class', 'form-control btn btn-danger']) }}
		</div>
	</div>
	{{ Form::close() }}

@endsection

resources/views/user/form.blade.php
@extends('template')

@section('content')
	@include('user.menu')
	@if (isset($user))
		{!! Form::model($user, ['route' => ['user.update', $user->id], 'files' => true, 'method' => 'PUT']) !!}
	@else
		{!! Form::open(['route' => 'user.store', 'files' => true]) !!}
	@endif

	<h2>Update your Account Details</h2>
	<div class="row">
		{!! Form::label('name', 'Name:', ['class' => 'col-lg-2 control-label']) !!}
		<div class="col-lg-10">
	    	{!! Form::text('name', null, ['class' => 'form-control']) !!}
		</div>
	</div>

	<div class="row">
		{!! Form::label('email', 'Email:', ['class' => 'col-lg-2 control-label']) !!}
		<div class="col-lg-10">
	    	{!! Form::text('email', null, ['class' => 'form-control']) !!}
		</div>
	</div>

	<div class="row">
		{!! Form::label('xbox_username', 'Xbox Username:', ['class' => 'col-lg-2 control-label']) !!}
		<div class="col-lg-10">
	    	{!! Form::text('xbox_username', null, ['class' => 'form-control']) !!}
		</div>
	</div>

	<div class="row">
		{!! Form::label('psn_username', 'PSN Username:', ['class' => 'col-lg-2 control-label']) !!}
		<div class="col-lg-10">
	    	{!! Form::text('psn_username', null, ['class' => 'form-control']) !!}
		</div>
	</div>

	<h2>Update your Shipping Details</h2>

	<div class="row">
		{!! Form::label('shipping_address1', 'Address 1:', ['class' => 'col-lg-2 control-label']) !!}
		<div class="col-lg-10">
	    	{!! Form::text('shipping_address1', null, ['class' => 'form-control']) !!}
		</div>
	</div>

	<div class="row">
		{!! Form::label('shipping_address2', 'Address 2:', ['class' => 'col-lg-2 control-label']) !!}
		<div class="col-lg-10">
	    	{!! Form::text('shipping_address2', null, ['class' => 'form-control']) !!}
		</div>
	</div>

	<div class="row">
		{!! Form::label('shipping_address3', 'Address 3:', ['class' => 'col-lg-2 control-label']) !!}
		<div class="col-lg-10">
	    	{!! Form::text('shipping_address3', null, ['class' => 'form-control']) !!}
		</div>
	</div>

	<div class="row">
		{!! Form::label('shipping_town', 'Town/City:', ['class' => 'col-lg-2 control-label']) !!}
		<div class="col-lg-10">
	    	{!! Form::text('shipping_town', null, ['class' => 'form-control']) !!}
		</div>
	</div>

	<div class="row">
		{!! Form::label('shipping_county', 'County:', ['class' => 'col-lg-2 control-label']) !!}
		<div class="col-lg-10">
	    	{!! Form::text('shipping_county', null, ['class' => 'form-control']) !!}
		</div>
	</div>

	<div class="row">
		{!! Form::label('shipping_postcode', 'Postcode:', ['class' => 'col-lg-2 control-label']) !!}
		<div class="col-lg-10">
	    	{!! Form::text('shipping_postcode', null, ['class' => 'form-control']) !!}
		</div>
	</div>

	<h2>Marketing Emails</h2>
	<p>{!! Form::checkbox('marketing_subscribe') !!} Please tick this box if you wish to be included in marketing emails (no more than two per week). We will keep you up to date on new games we have in, or new services we offer. You can unsubscribe via a one-click link in the footer to any email we send out, or simply untick this box. </p> 

	<div class="row">
		<div class="col-lg-12">
			{{ Form::submit('Update User Details', ['class' => 'form-control btn btn-primary']) }}
		</div>
	</div>

	{!! Form::close() !!}

@endsection

resources/views/user/history.blade.php
@extends('template')

@section('content')
	@include('user.menu')

	<h2>My Game Rental History</h2>

	<div class="row">
		<div class="col-2">Date of Rental</div>
		<div class="col-2">Game</div>
		<div class="col-2">System</div>
		<div class="col-2">Date of Return</div>
		<div class="col-2">Returned in Good Condition?</div>
		<div class="col-2">Length of Rental</div>
	</div>
	
	@foreach ($rentals as $rental)
		<div class="row">
			<div class="col-2">{{ $rental->date_of_delivery }}</div>
			<div class="col-2"><a href="{{ route('game.show', $rental->game->slug) }}">{{ $rental->game->name }}</a></div>
			<div class="col-2">{{ $rental->game->system->name }}</div>
			<div class="col-2">{{ $rental->date_of_return }}</div>
			<div class="col-2">{{ $rental->returned_ok }}</div>
			<div class="col-2">{{ $rental->length_of_rental }}</div>
		</div>
	@endforeach

@endsection

resources/views/user/invoicelist.blade.php
@extends('template')

@section('content')
	@include('user.menu')

	<h2>Invoice List</h2>

	<div class="row">
		<div class="col-2">Invoice #</div>
		<div class="col-2">Date</div>
		<div class="col-2">Date Shipped</div>
		<div class="col-2">Net</div>
		<div class="col-2">VAT</div>
		<div class="col-2">Total</div>
	</div>
	
	@foreach ($invoices as $invoice)
		<div class="row">
			<div class="col-2"><a href="{{ route('user.invoiceshow', $invoice->id) }}">{{ $invoice->id }} (show)</a></div>
			<div class="col-2">{{ $invoice->date_of_invoice }}</div>
			<div class="col-2">{{ $invoice->date_of_shipping }}</div>
			<div class="col-2">{{ $invoice->net }}</div>
			<div class="col-2">{{ $invoice->vat }}</div>
			<div class="col-2">{{ $invoice->gross }}</div>
		</div>
	@endforeach

@endsection

resources/views/user/invoiceshow.blade.php
@extends('template')

@section('content')
	@include('user.menu')

	<h2>Invoice #{{ $invoice->id }}</h2>

	<div class="row">
		<div class="col-12 col-md-4">
			<div class="card">
				<div class="card-header"><b>Invoice Information:</b></div>
				<div class="card-body">{!! $invoice->formatted_user_info !!}</div>
			</div>
		</div>
		<div class="col-12 col-md-4">
			<div class="card">
				<div class="card-header"><b>Shipping Address:</b></div>
				<div class="card-body">{!! $invoice->formatted_shipping_address !!}</div>
			</div>
		</div>
		<div class="col-12 col-md-4">
			<div class="card">
				<div class="card-header"><b>Billing Address:</b></div>
				<div class="card-body">{!! $invoice->formatted_billing_address !!}</div>
			</div>
		</div>
	</div>

	<h2>Invoice Lines</h2>
	<table class="table table-hover table-bordered table-sm table-responsive">
		<thead class="thead-default">
			<tr>
				<th>Qty</th>
				<th>Product</th>
				<th>Net</th>
				<th>Price with VAT</th>
			</tr>
		</thead>
		<tbody>
			@foreach ($invoice->lines as $line)
				{!! $line->box !!}
			@endforeach
			<tr>
				<td>&nbsp;</td>
				<td>Subtotal:</td>
				<td class="text-right">{{ $invoice->getFormattedValue('lines_net') }}</td>
				<td class="text-right">{{ $invoice->getFormattedValue('lines_gross') }}</td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td>Shipping:</td>
				<td class="text-right">{{ $invoice->getFormattedValue('shipping_net') }}</td>
				<td class="text-right">{{ $invoice->getFormattedValue('shipping_gross') }}</td>
			</tr>
			<tr class="table-success">
				<td>&nbsp;</td>
				<td>Total:</td>
				<td class="text-right">{{ $invoice->getFormattedValue('net') }}</td>
				<td class="text-right">{{ $invoice->getFormattedValue('gross') }}</td>
			</tr>
		</tbody>
	</table>

@endsection

resources/views/user/menu.blade.php
	<ul class="nav nav-pills nav-justified">
	  <li class="nav-item">
	    <a class="nav-link @if(Route::is('user.account')) active @endif" href="{{ route('user.account') }}">Wishlist</a>
	  </li>
	  <li class="nav-item">
	    <a class="nav-link @if(Route::is('user.agelimit')) active @endif" href="{{ route('user.agelimit') }}">Age Limit</a>
	  </li>
	  <li class="nav-item">
	    <a class="nav-link @if(Route::is('user.subscription')) active @endif" href="{{ route('user.subscription') }}">Subscriptions</a>
	  </li>
	  <li class="nav-item">
	    <a class="nav-link @if(Route::is('user.history')) active @endif" href="{{ route('user.history') }}">Game Rental History</a>
	  </li>
	  <li class="nav-item">
	    <a class="nav-link @if(Route::is('user.invoicelist')) active @endif" href="{{ route('user.invoicelist') }}">Invoices</a>
	  </li>
	  <li class="nav-item">
	    <a class="nav-link @if(Route::is('user.edit')) active @endif" href="{{ route('user.edit') }}">Edit Details</a>
	  </li>
	</ul>