routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/********************
* ROUTES - STATIC
********************/
Route::get('/', 'GameController@homepage')->name('home');

/********************
* ROUTES - PAGES
********************/
Route::get('page', 'PageController@index')->name('page.index');
Route::post('page', 'PageController@store')->name('page.store');
Route::get('page/create', 'PageController@create')->name('page.create');
Route::post('page/addcomment', 'PageController@addComment')->name('page.addcomment');
Route::put('page/{id}', 'PageController@update')->name('page.update');
Route::delete('page/{id}', 'PageController@destroy')->name('page.destroy');
Route::get('page/{slug}/edit', 'PageController@edit')->name('page.edit');

/********************
* ROUTES - GAMES
********************/
Route::get('game', 'GameController@index')->name('game.index');
Route::post('game', 'GameController@store')->name('game.store');
Route::get('game/create', 'GameController@create')->name('game.create');
//Because we might want to create a static page starting with "rent-", we have provision in the GameController@show method to push any unfound games to the appropriate PageController@show function. 
Route::get('rent-{game}', 'GameController@show')->name('game.show');
Route::get('achievements-{game}', 'GameController@achievements')->name('game.achievements');
Route::put('game/{game}', 'GameController@update')->name('game.update');
Route::delete('game/{game}', 'GameController@destroy')->name('game.destroy');
Route::get('game/{game}/edit', 'GameController@edit')->name('game.edit');
Route::post('game/addtowishlist', 'GameController@addToWishlist')->name('game.addtowishlist');
Route::post('game/deletefromwishlist', 'GameController@deleteFromWishlist')->name('game.deletefromwishlist');
Route::get('search-games', 'GameController@search')->name('game.search');

/********************
* ROUTES - PLAN
********************/
Route::get('plan', 'PlanController@index')->name('plan.index');
Route::post('plan-store', 'PlanController@store')->name('plan.store');
Route::get('plan/thanks', 'PlanController@thanks')->name('plan.thanks');
Route::get('plan/{slug}', 'PlanController@show')->name('plan.show');

/********************
* ROUTES - PRODUCTS
********************/
Route::get('cart', 'ProductController@cart')->name('product.cart');
Route::get('cart2', 'ProductController@cart2')->name('product.cart2');
Route::post('cart3', 'ProductController@cart3')->name('product.cart3');
Route::post('cart4', 'ProductController@cart4')->name('product.cart4');
Route::post('cart', 'ProductController@cartPost')->name('product.cartpost');
Route::get('product', 'ProductController@index')->name('product.index');
Route::post('product/addtocart', 'ProductController@addToCart')->name('product.addtocart');
Route::get('/product/convertcart', 'ProductController@convertCart')->name('product.convertcart');
Route::get('buy-{slug}', 'ProductController@show')->name('product.show');
Route::get('category-{slug}', 'ProductController@showcategory')->name('product.showcategory');

/********************
* ROUTES - USER
********************/
Route::get('user/account', 'UserController@account')->name('user.account');
Route::post('user/accountupdate', 'UserController@accountUpdate')->name('user.accountupdate');
Route::get('user/agelimit', 'UserController@ageLimit')->name('user.agelimit');
Route::get('user/agelimitconfirm/{hash}', 'UserController@ageLimitConfirm')->name('user.agelimitconfirm');
Route::post('user/agelimitupdate', 'UserController@ageLimitUpdate')->name('user.agelimitupdate');
Route::get('user/edit', 'UserController@edit')->name('user.edit');
Route::get('user/history', 'UserController@history')->name('user.history');
Route::get('user/invoice/{id}', 'UserController@invoiceShow')->name('user.invoiceshow');
Route::get('user/invoices', 'UserController@invoiceList')->name('user.invoicelist');
Route::get('user/subscription', 'UserController@subscription')->name('user.subscription');
Route::post('user/subscription/cancel', 'UserController@cancelSubscription')->name('user.cancelsubscription');
Route::post('user/subscription/resume', 'UserController@resumeSubscription')->name('user.resumesubscription');
Route::put('user/update', 'UserController@update')->name('user.update');
Route::post('user/register', 'UserController@registerPost')->name('user.register');
Route::get('user/registeraddress', 'UserController@registerAddress')->name('user.registeraddress');

/********************
* ROUTES - ADMIN
********************/
Route::get('admin/', 'AdminController@admin')->name('admin.admin');
Route::post('admin/assignment-run', 'AdminController@assignmentRun')->name('admin.assignmentrun');
Route::get('admin/competitors', 'AdminController@competitors')->name('admin.competitors');
Route::post('admin/competitors-post', 'AdminController@competitorsPost')->name('admin.competitorspost');
Route::post('admin/confirm-assignments', 'AdminController@confirmassignments')->name('admin.confirmassignments');
Route::get('admin/games/{numberofdays?}/{limit?}', 'AdminController@gameIndex')->name('admin.gameindex');
Route::post('admin/games-post', 'AdminController@gameIndexPost')->name('admin.gameindexpost');
Route::get('admin/igdb/{name}', 'AdminController@IGDBSearch')->name('admin.igdbsearch');
Route::get('admin/printdeliverynote/{id}', 'AdminController@printDeliveryNote')->name('admin.printdeliverynote');
Route::get('admin/product/create/', 'AdminController@productCreate')->name('admin.productcreate');
Route::get('admin/product/edit/{id}', 'AdminController@productEdit')->name('admin.productedit');
Route::get('admin/product/', 'AdminController@productIndex')->name('admin.productindex');
Route::post('admin/product/', 'AdminController@productStore')->name('admin.productstore');
Route::put('admin/product/', 'AdminController@productUpdate')->name('admin.productupdate');
Route::get('admin/rentals', 'AdminController@rentals')->name('admin.rentals');
Route::post('admin/rentals-update', 'AdminController@rentalsUpdate')->name('admin.rentalsupdate');
Route::get('admin/send-games', 'AdminController@sendGames')->name('admin.sendgames');
Route::get('admin/stock/', 'AdminController@stockIndex')->name('admin.stockindex');
Route::get('admin/stock/{id}', 'AdminController@stock')->name('admin.stock');
Route::post('admin/stock-update', 'AdminController@stockUpdate')->name('admin.stockupdate');
Route::get('admin/upload-games', 'AdminController@uploadGames')->name('admin.uploadgames');
Route::post('admin/upload-games-post', 'AdminController@uploadGamesPost')->name('admin.uploadgamespost');
Route::get('admin/upload-stock', 'AdminController@uploadStock')->name('admin.uploadstock');
Route::post('admin/upload-stock-post', 'AdminController@uploadStockPost')->name('admin.uploadstockpost');
Route::any('admin/users', 'AdminController@users')->name('admin.users');

Route::get('admin/testmail', 'AdminController@testMail')->name('admin.testmail');

/********************
* ROUTES - CONTACT
********************/
Route::get('contact', 'ContactController@create')->name('contact.create');
Route::get('contact/index', 'ContactController@index')->name('contact.index');
Route::get('contact/attachment/{slug}', 'ContactController@attachment')->name('contact.attachment');
Route::post('contact/send', 'ContactController@store')->name('contact.store');
Route::get('contact/show/{id}', 'ContactController@show')->name('contact.show');
Route::post('contact/update/', 'ContactController@update')->name('contact.update');

/********************
* ROUTES - OTHER
********************/
Route::get('braintree/token', 'BraintreeTokenController@token');
Route::post('braintree/webhook', 'WebhookController@handleWebhook');

Auth::routes();
Route::get('log-out', 'Auth\LoginController@logout')->name('log-out');

Route::get('login/{provider}', 'Auth\SocialAccountController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\SocialAccountController@handleProviderCallback');

Route::get('sitemap', 'SitemapController@index')->name('sitemap');

Route::get('{slug}', 'PageController@show')->where('slug', '(.*)')->name('page.show');

app/Plan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Plan extends Model
{
	protected $fillable = ['name', 'slug', 'braintree_plan', 'cost', 'description', 'max_games_simultaneously', 'is_premium', 'is_priority', 'max_games_per_month'];
    protected $table = 'plans';

    public function getBoxAttribute()
    {
        return '<div class="row">
                    <div class="col-12">'.e($this->name).'</div>
                </div>
                <div class="row">
                    <div class="col-12">'.e($this->description).'</div>
                </div>
                <div class="row">
                    <div class="col-2">'.e($this->max_games_simultaneously).'</div>
                    <div class="col-10">Simultaneous Games</div>
                </div>
                <div class="row">
                    <div class="col-2">'.e($this->is_premium_yes_no).'</div>
                    <div class="col-10">Premium Games Included</div>
                </div>
                <div class="row">
                    <div class="col-2">'.e($this->is_priority_yes_no).'</div>
                    <div class="col-10">Priority Service</div>
                </div>';
    }

    public function getIsPremiumYesNoAttribute()
    {
        if ($this->is_premium)
        {
            return 'Yes';
        } else {
            return 'No';
        }
    }

    public function getIsPriorityYesNoAttribute()
    {
        if ($this->is_priority)
        {
            return 'Yes';
        } else {
            return 'No';
        }
    }

    public function getMaxGamesPerMonthFormattedAttribute()
    {
    	if ($this->max_games_per_month > 10)
    	{
    		return 'Unlimited';
    	}

    	return $this->max_games_per_month;
    }

    public function subscriptions()
    {
        return $this->hasMany('App\Subscription', 'plan_id');
    }
}

app/Http/Controllers/PlanController.php
<?php

namespace App\Http\Controllers;

use App\Mail\SubscriptionChange;
use App\Mail\SubscriptionNew;
use App\Plan;
use Auth;
use Illuminate\Http\Request;
use Mail;

class PlanController extends Controller
{
    public function index()
    {
        return view('plans.index')->with(['plans' => Plan::where('is_visible', 1)->get()]);
    }

    public function show($id)
    {
      	$plan = Plan::where('slug', $id)->firstOrFail();
        if (Auth::check())
        {
            if (Auth::user()->isOnPlan($plan))
            {
                //Then user is already subscribed to this plan
                $showPurchaseForm = false;
            } else {
                $showPurchaseForm = true;
            }
        } else {
            $showPurchaseForm = false;
        }
        

        return view('plans.show')->with(['plan' => $plan, 'showPurchaseForm' => $showPurchaseForm]);
    }

    public function store(Request $request)
    {
        // get the plan after submitting the form
        $plan = Plan::find($request->plan_id);

        if (!$plan)
        {
            session()->flash('danger', 'Plan not found.');
            return redirect()->route('home');
        }

        if (!Auth::check())
        {
            session()->flash('danger', 'You are not logged in.');
            return redirect()->route('home');
        }

        Auth::user()->worldpay_token = $request->token;
        Auth::user()->save();

        //The subscribeTo() function takes care of whether we want to switch or do a new subscription. 
        if (Auth::user()->subscribeTo($plan))
        {
            // redirect to home after a successful subscription
            return redirect()->route('plan.thanks')->with('data', ['plan' => $plan->name, 'user' => $request->user()->firstname]);
        } else {
            //session()->flash('danger', 'There was an unidentified error');
            return redirect()->route('plan.show', $plan->slug);
        }

    }

    public function thanks()
    {
        return view('plans.thanks');
    }
}

resources/views/plans/index.blade.php
@extends('template')

@section('breadcrumbs')
    {{ Breadcrumbs::render('homeroute', 'All Game Rental Plans') }}
@endsection

@section('h1')
Video Game Rental Plans from Andach Game Rental
@endsection

@section('title')
Value and Unlimited Video Game Rental Plans | Andach Games
@endsection

@section('meta-description')
Rent video games from Andach Games with plans available from &pound;3.99 per month, with unlimited video game rental at just &pound;9.99 per month. Free postage both ways, no contracts. 
@endsection

@section('content')
<h2>Game Rental Plans</h2>
<p>We have a variety of game rental plans available. They're differentiated by the number of games you can play in a month, and the number of games you can have at one time. </p>
<p>Our priority service is for customers who want to play the latest games, or want to pay a little extra to ensure they have their top choices much more of the time. It's simple. The game allocation script runs once for priority customers, fills up all their choices, then runs for non-priority customers. There's no other difference. </p>
<p>This means that the latest games will likely go to priority customers until they've all had the opportunity to play them and sent them back - at which point everybody can have them. But we don't believe in restricting our games artificially so they're available for everybody if nobody else wants them. </p>

@if (!Auth::check())
<p class="alert alert-warning"><b>You aren't logged in:</b> - You can only subscribe to a plan with an account. Either <a href="{{ route('login') }}">login</a> or <a href="{{ route('register') }}">register</a>, then come back here to get subscribed and play your new games within days!</p>
@else
	@if(Auth::user()->isSubscribed())
		<p class="alert alert-warning"><b>You are already subscribed to a plan.</b> Please only pay for a new plan here if you want to switch.</p>
	@else
		<p class="alert alert-success">You are currently logged in as <b>{{ Auth::user()->name }}</b> and are not subscribed to a plan. So don't hesitate!</p>
	@endif
@endif

<h2>Pick a Rental Plan</h2>
<div class="row">
	<div class="col-2">Name</div>
	<div class="col-2"># of Games at a Time</div>
	<div class="col-2"># of Games per Month</div>
	<div class="col-2">Priority?</div>
	<div class="col-2">Price per Month</div>
	<div class="col-2">Buy</div>
</div>


<div class="divzebra">
@foreach ($plans as $plan)
<div class="row">
	<div class="col-2">{{ $plan->name }}</div>
	<div class="col-2">{{ $plan->max_games_simultaneously }}</div>
	<div class="col-2">{{ $plan->max_games_per_month_formatted }}</div>
	<div class="col-2">
		@if ($plan->is_priority)
			<img src="/images/template/tick.svg" height="32px">
		@else
			<img src="/images/template/cross.svg" height="32px">
		@endif
	</div>
	<div class="col-2">&pound;{{ number_format($plan->cost, 2) }}</div>
	<div class="col-2">
		<a href="{{ route('plan.show', $plan->slug) }}">
			<button class="btn btn-success">Choose Plan</button>
		</a>
	</div>
</div>
@endforeach
</div>
@endsection

resources/views/plans/show.blade.php
@extends('template')

@section('google-analytics')
  gtag('set', {'content_group1': 'Plans'}); 
@endsection

@section('breadcrumbs')
    {{ Breadcrumbs::render('plan', $plan) }}
@endsection

@section('h1')
The {{ $plan->name }} game rental service.
@endsection

@section('meta-description')
Rent {{ $plan->max_games_simultaneously }} video games at a time for &pound;{{ number_format($plan->cost, 2) }} per month. 
@endsection

@section('title')
The {{ $plan->name }} game rental service. | Andach Game Rentals | Rent &amp; Buy Video Games
@endsection

@section('content')
<div class="container">

  {!! $plan->box !!}

@if(Auth::check())  

  @if(Auth::user()->isSubscribed())

    @if (Auth::user()->isOnPlan($plan))
    <div class="row">
      <div class="col-12 alert alert-danger">
        You are already subscribed to this plan. 
      </div>
    </div>
    @else
    <div class="row">
      <div class="col-12 alert alert-warning">
        <b>You are already subscribed to plan - <a href="{{ route('plan.show', Auth::user()->currentPlan()->slug) }}">{{ Auth::user()->currentPlan()->name }}</a>.</b> Please only pay for a new plan here if you want to switch.
      </div>
    </div>
    @endif
  @endif


  @if ($showPurchaseForm)
  <h2>Please Pay Below</h2>
  <p>You'll need to wait just a few seconds for the form below to load. Please note that you need to provide your <i>billing</i> post code to the form, not your delivery post code.</p>
  <form method="post" id="paymentForm" action="{{ route('plan.store') }}">
      {{ csrf_field() }}
      {{ Form::hidden('plan_id', $plan->id) }}

      <span id="paymentErrors"></span>

      <div class="row">
        <div class="col-2">
          <label>Name on Card</label>
        </div>
        <div class="col-10">
          <input data-worldpay="name" name="name" type="text" class="form-control" />
        </div>
        <div class="col-2">
          <label>Card Number</label>
        </div>
        <div class="col-10">
          <input data-worldpay="number" size="20" type="text" class="form-control" />
        </div>
        <div class="col-2">
          <label>Expiration (MM/YYYY)</label> 
        </div>
        <div class="col-10">
          <input data-worldpay="exp-month" size="2" type="text" class="form-control" /> 
          <label> / </label>
          <input data-worldpay="exp-year" size="4" type="text" class="form-control" />
        </div>
        <div class="col-2">
          <label>CVC</label>
        </div>
        <div class="col-10">
          <input data-worldpay="cvc" size="4" type="text" class="form-control" />
        </div>
      </div>
      
      {{ Form::submit('Sign Up!', ['class' => 'form-control btn btn-success']) }}
  </form>
  @endif

</div>
@else
  <p class="alert alert-danger"><b>You aren't logged in:</b> - You can only subscribe to a plan with an account. Either <a href="{{ route('login') }}">login</a> or <a href="{{ route('register') }}">register</a>, then come back here to get subscribed and play your new games within days!</p>
@endif

</div>

@endsection

@section('javascript')
<script src="https://cdn.worldpay.com/v1/worldpay.js"></script>

<script type="text/javascript">
var form = document.getElementById('paymentForm');

Worldpay.useOwnForm({
  'clientKey': '{{ env('WORLDPAY_CLIENT_KEY') }}',
  'form': form,
  'reusable': true,
  'callback': function(status, response) {
    document.getElementById('paymentErrors').innerHTML = '';
    if (response.error) {             
      Worldpay.handleError(form, document.getElementById('paymentErrors'), response.error); 
    } else {
      var token = response.token;
      Worldpay.formBuilder(form, 'input', 'hidden', 'token', token);
      form.submit();
    }
  }
});
</script>
@endsection

resources/views/plans/thanks.blade.php
@extends('template')

@section('content')
<div class="container">

  <h2>Subscription Successful</h2>
  <p>Thanks, you have successfully subscribed to your plan. Make sure to add some games to your wishlist and we'll get them to you via first class post!</p>

</div>
@endsection